version: '3.7'
networks:
  dspacenet:
services:
  dspace-angular:
    container_name: dspace.poc.euraknos.cf
    environment:
      DSPACE_HOST: dspace.poc.euraknos.cf
      DSPACE_NAMESPACE: /
      DSPACE_PORT: '80'
      DSPACE_SSL: "false"
    image: dspace/dspace-angular:latest
    build:
      context: ..
      dockerfile: Dockerfile
    networks:
      dspacenet:
    ports:
    - published: 3000
      target: 4000
#      target: 80
    - published: 9876
      target: 9876
    stdin_open: true
    tty: true
    volumes:
    - ./environment.dev.ts:/app/src/environments/environment.dev.ts
